### ISSUE TITLE
About octave

### ISSUE THREAD

**Issue by ioyy900205** [seorim0/Speech_enhancement_with_Pytorch#4]
Hello, dear author.

I would like to use MOS tool under tools_for_estimate.py. But I am prompted that I need the octave component. It took me a long time to install it but it didn't work. I would like to ask the author how to install it. Or is there a dockerfile available?

**Comment by seorim0** [comment]
Hi!   
I'm sorry to there is no dockerfile available.    
Octave must be installed 
```
apt install octave
pip install oct2py Cython # install Cython before installing pesq
pip install pesq
```   
Or, if you want to use metrics for CSIG, CBAK, COVL, I found some easy-to-use Python code, not Matlab.   
Here is the Github repository: https://github.com/santi-pdp/segan_pytorch/blob/052238718b037cd72c7fa69bc1577782e5ef015d/segan/utils.py#L397   
  
You probably won't suffer from octave with this code.
