### ISSUE TITLE
nested Unet

### ISSUE THREAD

**Issue by wendongj** [seorim0/Speech_enhancement_with_Pytorch#5]
Hi, I see your new project of nested Unet in today afternoon, when I prepare to see more details, seems this project was deleted, that result is much better than DCCRN-E and Fullsubnet, hope to see it agian...

**Comment by seorim0** [comment]
Oh, I made the repo public for about 2 hours, and you saw it then.   
OK, I'll switch back it to public.   
I did not upload our paper, so it may be difficult to interpret just by looking at the repo.   
If you have any questions, ask me again.   

Although we did not show the result compared to DCCRN-E in our paper, our proposed model showed better PESQ than DCCRN-E by about 0.4 or more.

**Comment by wendongj** [comment]
I see it yesterday, really thanks for reply, covid19 in korea is still severe, please take care of yourself.

**Comment by seorim0** [comment]
Thank you for your concern! I wish you good health too.
